apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deployment
  labels:
    app: predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor-container
        image: abdulrhmanmokhtar/predictor-real-estate:v1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: predictor-service
spec:
  selector:
    app: predictor
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
